[project]
name = "pythonKitchen"
version = "0.1.6"
description = "Package description for pythonKitchen"
readme = "README.md"
requires-python = ">=3.11,<4.0"
license = { text = "MIT" }
authors = [
  { name = "Suhail", email = "suhailece@gmail.com" },
]
dependencies = [
  "beautifulsoup4 >=4.13.4,<5.0.0",
  "browser-cookie3 >=0.20.1,<0.21.0",
  "incept >=0.1.78,<0.2.0",
  "ledu >=0.1.3,<0.2.0",
  "lumiera >=0.1.3,<0.2.0",
  "notion-client >=2.3.0,<3.0.0",
  "oauthmanager >=0.1.1,<0.2.0",
  "openai >=1.76.0,<2.0.0",
  "openpyxl >=3.1.5,<4.0.0",
  "pandas >=2.2.3,<3.0.0",
  "parivaha >=0.1.16,<0.2.0",
  "pillow >=11.2.1,<12.0.0",
  "prefect[github] >=3.1.5,<4.0.0",
  "pypdf >=5.5.0,<6.0.0",
  "pytesseract >=0.3.13,<0.4.0",
  "python-dotenv >=1.1.0,<2.0.0",
  "requests >=2.32.3,<3.0.0",
  "selenium >=4.31.0,<5.0.0",
  "tabulate >=0.9.0,<0.10.0",
  "webdriver-manager >=4.0.2,<5.0.0",
]
[project.optional-dependencies]
dev = [
  "build ^1.2.2.post1",
  "twine >=6.1.0,<7.0.0",
]
[project.scripts]
pythonkitchen = "pythonkitchen.cli:main"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

# Original [tool.poetry] has been migrated to PEP 621 by migrate2uv.sh
